# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w9PdSfGxz5kcB4fdlmlGapUjIR5jjWsp
"""

import openai
import gradio
import os 

client = openai.OpenAI(api_key="")  

messages = [{"role": "system", "content": "You are an hospital staff who dealt with patient with healthcare"}]

def CustomChatGPT(user_input):
    try:
        messages.append({"role": "user", "content": user_input})
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=messages
        )
        ChatGPT_reply = response.choices[0].message.content
        messages.append({"role": "assistant", "content": ChatGPT_reply})
        return ChatGPT_reply
    except openai.OpenAIError as e:
        return f"Error: {str(e)}"
    except Exception as e:
        return f"Unexpected error: {str(e)}"


demo = gradio.Interface(
    fn=CustomChatGPT,
    inputs=gradio.Textbox(label="Ask a question"), 
    outputs=gradio.Textbox(label="Response"),  
    title="Chatbot Rumah Sakit"
)

demo.launch(share=True)